# stage : 단계. 우리의 경우에는 build-push와 같은 형태의 하나의 단계만 존재
stages: 
  - dockerbuild-push

package:
  image: docker:latest
  stage: dockerbuild-push
  services:
    - docker:dind
  before_script:
			#docker 로그인
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PASSWORD
  script:
    - docker build -t registry.gitlab.com/$GITLAB_USER/likelion-hospital-review .
    - docker push registry.gitlab.com/$GITLAB_USER/likelion-hospital-review
  after_script:
    - docker logout